export { loadDoc, saveDoc } from './doc'
export { reanchorMarks } from './reanchor'
export { applySuggestion } from './apply'
export { hasFooterConflict, resolveFooterConflictText } from './footer'
export { history, diff, commitFile, isGitRepo } from './git'
export { buildMarkIndex, findFileForMark, listManagedDocs } from './markindex'
export type { MarkIndex } from './markindex'
export { createSession, serve } from './serve'
export type { Session, SessionOptions, ServeOptions, ServeHandle } from './serve'
export { createCollabServer, configureCollab } from './collab'
export type { CollabServerOptions, CollabServerHandle, ConfiguredCollab } from './collab'
export { serveShare } from './share'
export type { ShareServeOptions, ShareServeHandle, ShareRole, ShareCapabilities } from './share'
export { createAgentApi } from './agent'
export type { AgentApi, AgentState, CommentInput, SuggestInput } from './agent'
export * from './types'
export * as proof from './proof'
export type { Mark, MarkKind, MarkRange, StoredMark } from './proof'
