export { loadDoc, saveDoc } from './doc'
export { reanchorMarks } from './reanchor'
export { hasFooterConflict, resolveFooterConflictText } from './footer'
export { history, diff, commitFile, isGitRepo } from './git'
export { createSession, serve } from './serve'
export type { Session, SessionOptions, ServeOptions, ServeHandle } from './serve'
export * from './types'
export * as proof from './proof'
export type { Mark, MarkKind, MarkRange, StoredMark } from './proof'
